export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";

export const SET_USER = "SET_USER";
export const AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";

export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";
export const SET_CLIENT_ERROR_MESSAGE = "SET_CLIENT_ERROR_MESSAGE";

export const FETCH_JOBS_SUCCESS = "FETCH_JOBS_SUCCESS";
export const FETCH_SINGLE_JOB_SUCCESS = "FETCH_SINGLE_JOB_SUCCESS";
export const CLEAR_SINGLE_JOB = "CLEAR_SINGLE_JOB";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const EDIT_JOB_SUCCESS = "EDIT_JOB_SUCCESS";
export const SET_EDIT_COMPLETE = "SET_EDIT_COMPLETE";
export const DELETE_JOB_SUCCESS = "DELETE_JOB_SUCCESS";
