export const START_LOADING = "SET_LOADING";

export const SET_USER = "SET_USER";
export const AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS";
export const AUTH_USER_ERROR = "AUTH_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";

export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";

export const FETCH_JOBS_SUCCESS = "FETCH_JOBS_SUCCESS";
export const FETCH_JOBS_ERROR = "FETCH_JOBS_ERROR";
